version: "3.7"

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /mnt/storage/dockerdata/sabnzbd:/config
      - /mnt/storage/download:/data/usenet
    ports:
      - 7070:8080
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`downloads.${DOMAINNAME}`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.tls.certresolver=myresolver"
      - "traefik.http.routers.sabnzbd.middlewares=secure-headers@docker"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://example.com
    volumes:
      - /mnt/storage/dockerdata/jellyfin/config:/config
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/kids:/data/kids
      - /mnt/storage/media/4kmovies:/data/4kmovies
      - /mnt/storage/media/tv:/data/tvshows
      - /mnt/storage/media/christmas:/data/christmas
    ports:
      - 8096:8096
      - 7359:7359/udp
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAINNAME}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.routers.jellyfin.middlewares=secure-headers@docker"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=traefik_proxy"

  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /mnt/storage/dockerdata/plex:/config
      - /mnt/storage/media:/data/media
      - /tmp:/transcode
    network_mode: host
    restart: unless-stopped
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ADVERTISE_IP="http://10.0.0.30:32400/"

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/storage/dockerdata/plex:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`plexstats.${DOMAINNAME}`)"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.tls.certresolver=myresolver"
      - "traefik.http.routers.tautulli.middlewares=secure-headers@docker"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.docker.network=traefik_proxy"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /mnt/storage/dockerdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ssl:/config/ssl
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`ha.${DOMAINNAME}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - "traefik.http.routers.homeassistant.middlewares=secure-headers@docker"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=traefik_proxy"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /mnt/storage/dockerdata/sonarr:/config
      - /mnt/storage/media/tv:/data/media/tv
      - /mnt/storage/download:/data/usenet
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`tv.${DOMAINNAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr.middlewares=secure-headers@docker"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=traefik_proxy"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - /mnt/storage/dockerdata/radarr:/config
      - /mnt/storage/media/:/data/media/
      - /mnt/storage/download:/data/usenet
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`movies.${DOMAINNAME}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr.middlewares=secure-headers@docker"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=traefik_proxy"

  readarr:
    image: hotio/readarr:nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/storage/dockerdata/readarr:/config
      - /mnt/storage/media/books/ebooks:/data/media/books
      - /mnt/storage/media/books/comics:/data/media/comics
      - /mnt/storage/download:/data/usenet
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`books.${DOMAINNAME}`)"
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.routers.readarr.tls.certresolver=myresolver"
      - "traefik.http.routers.readarr.middlewares=secure-headers@docker"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - "traefik.docker.network=traefik_proxy"

  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /mnt/storage/dockerdata/ubooquity:/config
      - /mnt/storage/media/books/ebooks:/books
      - /mnt/storage/media/books/comics:/comics
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ubooquity.rule=Host(`opds.${DOMAINNAME}`)"
      - "traefik.http.routers.ubooquity.entrypoints=websecure"
      - "traefik.http.routers.ubooquity.tls=true"
      - "traefik.http.routers.ubooquity.tls.certresolver=myresolver"
      - "traefik.http.routers.ubooquity.middlewares=secure-headers@docker"
      - "traefik.http.services.ubooquity.loadbalancer.server.port=2202"
      - "traefik.docker.network=traefik_proxy"

  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 9696:9696
    volumes:
      - /mnt/storage/dockerdata/prowlarr/config:/config
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`index.${DOMAINNAME}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=myresolver"
      - "traefik.http.routers.prowlarr.middlewares=secure-headers@docker"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.docker.network=traefik_proxy"

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /mnt/storage/dockerdata/overseerr/config:/app/config
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`request.${DOMAINNAME}`)"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=myresolver"
      - "traefik.http.routers.overseerr.middlewares=secure-headers@docker"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik_proxy"

  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /mnt/storage/dockerdata/ubooquity:/config
      - /mnt/storage/media/books/comics:/data
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`comics.${DOMAINNAME}`)"
      - "traefik.http.routers.komga.entrypoints=websecure"
      - "traefik.http.routers.komga.tls=true"
      - "traefik.http.routers.komga.tls.certresolver=myresolver"
      - "traefik.http.routers.komga.middlewares=secure-headers@docker"
      - "traefik.http.services.komga.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"

volumes:
  ssl:

networks:
  traefik_proxy:
    external: true # Shared external proxy network on host
